# Generated by Django 3.1.5 on 2021-01-29 02:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('blockers', models.ManyToManyField(blank=True, related_name='dependents', to='tasks.Task')),
                ('categories', models.ManyToManyField(blank=True, to='tasks.Category')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.project')),
            ],
            options={
                'ordering': ['done', 'created_date', 'text'],
            },
        ),
    ]
