# Generated by Django 3.1.5 on 2021-01-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', 'blocked']},
        ),
        migrations.AddField(
            model_name='task',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
